version: "3"
services:
  telldus-core-alpine:
    image: mliljedahl/telldus-core-alpine
    container_name: telldus-core-alpine
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    volumes:
      - ./data/tellstick.conf:/etc/tellstick.conf:ro
    ports:
      - "50800:50800"
      - "50801:50801"
